import type { Metadata } from "next";
import "./globals.css";
import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from "@mantine/core";
import { NavbarMinimal } from "./components/navbar/navbarminimal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Adjust the width as needed for your navbar
  const navbarWidth = "250px";

  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          
          <NavbarMinimal />
          <main style={{marginLeft :"200px"}}>
         
            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
